### ISSUE TITLE
Index table "Exact AND" keyword logic issue when post ID search is enabled

### ISSUE THREAD

**Issue by ernestmarcinko** [WPDreams/ajax-search-pro-development#121]
### Describe the bug
The Index Table search seems to exclude some matches when the **AND with exact keyword matches** primary logic is selected.
The issue is related to the post ID search and the function mergeRawResults, where the merge does not treat the Post ID query matches separately and the intersection of arrays return short of potential matches.

### TODO
- [x] The exact title & CF query array key should be a string
- [x] The "starts with" title & CF query array keys should also be a string
- [x] The post ID query key should be also keyed in the query array
- [x] The mergeRawResults method should deal with the above matches
