### ISSUE TITLE
Advanced title and content field array values should be converted automatically to string + separator

### ISSUE THREAD

**Issue by ernestmarcinko** [WPDreams/ajax-search-pro-development#82]
### Describe the bug
When not using ACF, if the field value is returned as an array or object, then it should be automatically converted to to a string.
An additional field argument should be implemented: `separator=","` which is used when joining the values.

### Todo
- [x] `Utils\Str::anyToString` signature should be changed to accept a delimiter, and level moved to the 3rd argument
- [x] `Utils\Str::anyToString` should also integrate `maybe_unserialize()` to properly convert the value
- [x] Make sure it's implemented in both `Post\getCFValue` and `User\getCFValue`
- [x] Add separator field argument
- [x] Test
- [x] Documentation

[Reference ticket.](https://wp-dreams.com/forums/topic/user-result-fields-url-array-in-result/#post-47072)

**Comment by ernestmarcinko** [comment]
Added to 4.26.5-dev and backend-refactor (via cherry pick)
