### ISSUE TITLE
Taxonomy filter to include items from sub-terms

### ISSUE THREAD

**Issue by ernestmarcinko** [WPDreams/ajax-search-pro-development#83]
Currently the taxonomy term filters will only apply to direct term to post type object relationships.

For example consider this taxonomy term structure:
```
Parent (0)
-- Child 1 (0)
---- Child 1-1 (2)
---- Child 1-2 (2)
-- Child 2 (0)
---- Child 2-1 (3)
---- Child 2-2 (3)
```
**Parent, Child 1 and Child 2** does not have any posts assigned, however their children do. Currently creating a filter with only **Child 1** and **Child 2** will not have any effect, as sub-terms are not considered:

Filter example, imagine as a checkbox:
```
-- Child 1 (0)
-- Child 2 (0)
```

This will yield 0 results or will have no effect whatsoever, regardless of the filter states.

## Todos
- [x] Add a back-end option: Filtering by parent terms should also include the results from children? (ON) - If a post from child category is not directly assigned to the parent category as well, this will force the filter to still apply if the parent category is selected.
- [x] Add a logic to the taxonomy argument parser
- [x] Add a logic to the archive page parser
