### ISSUE TITLE
PDF thumbnails should be fetched first & respect size

### ISSUE THREAD

**Issue by ernestmarcinko** [WPDreams/ajax-search-pro-development#85]
### Describe the bug
PDF thumbnails are only fetched when the $r->image is empty, but this causes an issue when a default image is set. 

### To Reproduce
1. Set a default image
2. Search for PDF
3. Instead of PDF image capture, the default is shown
4. The size is also incorrect

### Expected behavior
The PDF image should be displayed instead of the default choice in the correctly selected size.

### TODO
- [x] Change the order of the image fetching
- [x] Improve thumbnail generator to respect the image dimensions
- [x] Add check for the internal images generated by WordPress
