### ISSUE TITLE
Search input in Wordpress Menu system

### ISSUE THREAD

**Issue by JCIWebAdmin** [WPDreams/ajax-search-pro-development#88]
Is it possible to add functionality whereby an ajax search input field is available in to the "menu items" in Wordpress' menu settings? This would allow integrating search input field in the main menu or a submenu – especially applicable for mobile menus.

Thank you
Richard Stevens

**Comment by ernestmarcinko** [comment]
Hi Richard,

This is already possible via adding the plugin shortcode [as a menu item](https://documentation.ajaxsearchpro.com/getting-started/search-as-menu-item). I will keep this open though, there might be a simple way of adding a meta box to the editor screen.

If it's not too difficult, then I can probably add it to the next release.

**Comment by ernestmarcinko** [comment]
Looks like this is going on a trial. Let's see if we can work out something.

### Todo
- [x] Add menu meta box with selection of isntances,
- [x] Add option (checkbox) to prevent default menu events via `jQuery('.asp_w_container').closest('.menu-item').off();` - this will prevent unwanted click/blur behavior
- [x] See if the menu item render can replace the container anchor to a div instead

### References
https://wordpress.stackexchange.com/questions/30347/how-to-add-meta-box-to-backend-menu-page
https://johnmorrisonline.com/how-to-add-a-fully-functional-custom-meta-box-to-wordpress-navigation-menus/
https://developer.wordpress.org/reference/functions/add_meta_box/

**Comment by ernestmarcinko** [comment]
This has been finished and merged to [4.26.6](https://github.com/WPDreams/ajax-search-pro/tree/4.26)
