### ISSUE TITLE
Script & CSS pollution in possible ajax cases

### ISSUE THREAD

**Issue by ernestmarcinko** [WPDreams/ajax-search-pro-development#92]
### Describe the bug
As previously addressed in #86 the issue seems to be possible to replicate when the user is not logged in.
Some exceptions seems to be set incorrectly and the output buffer gets polluted with the incorrect output.

### Todo
- [x] Check the exceptions in Asset\CSS\Manager()
- [x] Make sure the exceptions are applied in Asset\Script\Manager() as well
- [x] Same for the Asset\Font\Manager()
- [x] If the conditions are equal, it should be moved to a common ancestor

**Comment by ernestmarcinko** [comment]
Fixed in https://github.com/WPDreams/ajax-search-pro/commit/cda5aa96b7dc6fd0b9d990aabd6f8300ed5cab0c
