### ISSUE TITLE
Asset manager issue in Breakdance editor when ajax is enabled

### ISSUE THREAD

**Issue by ernestmarcinko** [WPDreams/ajax-search-pro-development#97]
### Describe the bug
When using Breakdance, saving a post can leat to an error message (however the post is saved still). It's because the asset manager tries to load the stylesheets, but incorrectly detects the template header.

This also happens to the menu in the header editor.

### Todos

- [x] Add a hook to the shortcode handler to $include_styles so that styles can be included 
```php
$include_styles = apply_filters('asp/shortcode/include_styles', $include_styles, $style, $id);
```
- [x] Refactor the CSS minify method to Utils/Css so it can be used in the shortcode handler
- [x] Update the CSS manager to use the Utils/Css minify
- [x] The Asset\Font::injectToBuffer() should have a compatibility check as well as it pollutes
- [x] Add a hook to the `asp/shortcode/include_styles` for `isset($_GET['_breakdance_doing_ajax'])`
